//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace eHealthServices.WYYY.Areas.HelpPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EH_Hospital
    {
        public int HID { get; set; }
        public string Secret { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string Level { get; set; }
        public string Category { get; set; }
        public string ShortInfo { get; set; }
        public string FullInfo { get; set; }
        public byte[] LogoImg { get; set; }
        public byte[] Panorama { get; set; }
        public Nullable<decimal> CenterPointE { get; set; }
        public Nullable<decimal> CenterPointN { get; set; }
        public string PointOne { get; set; }
        public string PointTwo { get; set; }
        public string PointThree { get; set; }
        public string PointFour { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> CityID { get; set; }
        public string ServiceURL { get; set; }
        public Nullable<System.DateTime> ExpireTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> Creater { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> Modifier { get; set; }
        public Nullable<int> Mode { get; set; }
        public string HAddress { get; set; }
    }
}
